version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_cleanarch
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 33306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 0s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_cleanarch
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  migrate:
    image: migrate/migrate
    restart: on-failure:10
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database",  "mysql://root:root@(mysql:3306)/orders", "-verbose", "up"]
    links: 
      - mysql:mysql
    depends_on:
      mysql:
        condition: service_healthy