// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Order struct {
	ID         string  `json:"id"`
	Price      float64 `json:"Price"`
	Tax        float64 `json:"Tax"`
	FinalPrice float64 `json:"FinalPrice"`
}

type OrderInput struct {
	ID    string  `json:"id"`
	Price float64 `json:"Price"`
	Tax   float64 `json:"Tax"`
}

type OrderListInput struct {
	Page  *int    `json:"page,omitempty"`
	Limit *int    `json:"limit,omitempty"`
	Sort  *string `json:"sort,omitempty"`
}

type Query struct {
}
